# Generated by Django 5.0.6 on 2024-07-09 02:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modulos', '0002_alter_modulo_options_modulo_descricao_modulo_order_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='modulo',
            name='order',
            field=models.PositiveIntegerField(db_index=True, editable=False, verbose_name='order'),
        ),
    ]
