# Generated by Django 5.0.6 on 2024-07-09 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modulos', '0003_alter_modulo_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='modulo',
            name='slug',
            field=models.SlugField(max_length=32, null=True),
        ),
    ]
